### ISSUE TITLE
Apache thrift core dumps at apps closing

### ISSUE THREAD

**Issue by primercuervo** [gnuradio/gnuradio-livesdr#13]
I was just testing the liveSDR image and checking the versions of UHD and GNURadio that come within, which are according to the documentation. 

Just before I finish my testing, I connected an USRP b200 and ran:

```
$ uhd_fft -f 2.4e9
```

which ran without issues, but segfaults at closing

```
ubuntu@ubuntu:/usr/local/src/pybombs_legacy/src$ uhd_fft -f 2.4e9
linux; GNU C++ version 4.8.4; Boost_105400; UHD_003.009.004-0-g2b5a88bb

-- Loading firmware image: /usr/local/share/uhd/images/usrp_b200_fw.hex...
-- Detected Device: B200
-- Loading FPGA image: /usr/local/share/uhd/images/usrp_b200_fpga.bin... done
-- Operating over USB 3.
-- Detecting internal GPSDO.... No GPSDO found
-- Initialize CODEC control...
-- Initialize Radio control...
-- Performing register loopback test... pass
-- Performing CODEC loopback test... pass
-- Asking for clock rate 16.000000 MHz... 
-- Actually got clock rate 16.000000 MHz.
-- Performing timer loopback test... pass
-- Setting master clock rate selection to 'automatic'.
-- Asking for clock rate 32.000000 MHz... 
-- Actually got clock rate 32.000000 MHz.
-- Performing timer loopback test... pass
gr::log :INFO: controlport - Apache Thrift: -h ubuntu -p 45365
Segmentation fault (core dumped)
```

Backtrace output:

```
6:10 PM (gdb) run /usr/local/bin/uhd_fft -f 2e9
The program being debugged has been started already.
Start it from the beginning? (y or n) yStarting program: /usr/bin/python2 /usr/local/bin/uhd_fft -f 2e9
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7fffe07bc700 (LWP 5438)]
[New Thread 0x7fffdffbb700 (LWP 5439)]
[New Thread 0x7fffdd7ba700 (LWP 5440)]
[New Thread 0x7fffdafb9700 (LWP 5441)]
[New Thread 0x7fffd87b8700 (LWP 5442)]
[New Thread 0x7fffd5fb7700 (LWP 5443)]
[New Thread 0x7fffd37b6700 (LWP 5444)]
linux; GNU C++ version 4.8.4; Boost_105400; UHD_003.009.004-0-g2b5a88bb[New Thread 0x7fffbe26d700 (LWP 5445)]
[New Thread 0x7fffbda6c700 (LWP 5446)]
[New Thread 0x7fffbc8f1700 (LWP 5447)]
[New Thread 0x7fffaffff700 (LWP 5448)]
[New Thread 0x7fffaf7fe700 (LWP 5449)]
[New Thread 0x7fffadcf7700 (LWP 5451)]
[New Thread 0x7fffad4f6700 (LWP 5452)]
[Thread 0x7fffad4f6700 (LWP 5452) exited]
[Thread 0x7fffadcf7700 (LWP 5451) exited]
[New Thread 0x7fffadcf7700 (LWP 5453)]
[New Thread 0x7fffad4f6700 (LWP 5454)]
[Thread 0x7fffad4f6700 (LWP 5454) exited]
[Thread 0x7fffadcf7700 (LWP 5453) exited]
[New Thread 0x7fffadcf7700 (LWP 5455)]
[New Thread 0x7fffad4f6700 (LWP 5456)]
-- Loading firmware image: /usr/local/share/uhd/images/usrp_b200_fw.hex...[Thread 0x7fffaffff700 (LWP 5448) exited][Thread 0x7fffad4f6700 (LWP 5456) exited]
[Thread 0x7fffadcf7700 (LWP 5455) exited]
[New Thread 0x7fffadcf7700 (LWP 5469)]
[New Thread 0x7fffad4f6700 (LWP 5470)]
[Thread 0x7fffad4f6700 (LWP 5470) exited]
[Thread 0x7fffadcf7700 (LWP 5469) exited]
[New Thread 0x7fffadcf7700 (LWP 5471)]
[New Thread 0x7fffad4f6700 (LWP 5472)]
-- Detected Device: B200
-- Loading FPGA image: /usr/local/share/uhd/images/usrp_b200_fpga.bin... done
-- Operating over USB 3.
[New Thread 0x7fffaffff700 (LWP 5473)]
-- Detecting internal GPSDO.... No GPSDO found
-- Initialize CODEC control...
-- Initialize Radio control...
-- Performing register loopback test... pass
-- Performing CODEC loopback test... pass
-- Asking for clock rate 16.000000 MHz... [Thread 0x7fffaf7fe700 (LWP 5449) exited]-- Actually got clock rate 16.000000 MHz.
-- Performing timer loopback test... pass
-- Setting master clock rate selection to 'automatic'.
-- Asking for clock rate 32.000000 MHz...
-- Actually got clock rate 32.000000 MHz.
-- Performing timer loopback test... pass
[New Thread 0x7fffaf7fe700 (LWP 5474)]
[New Thread 0x7fffac959700 (LWP 5475)]
[New Thread 0x7fff9ffff700 (LWP 5476)]
[New Thread 0x7fff9f7fe700 (LWP 5477)]
[New Thread 0x7fff9effd700 (LWP 5478)]
gr::log :INFO: controlport - Apache Thrift: -h ubuntu -p 46234
[New Thread 0x7fff9e7fc700 (LWP 5479)]
[New Thread 0x7fff9dffb700 (LWP 5480)]
[New Thread 0x7fff9d7fa700 (LWP 5481)]
[New Thread 0x7fff9cff9700 (LWP 5482)]
[Thread 0x7fffac959700 (LWP 5475) exited]
[New Thread 0x7fffac959700 (LWP 5483)]
[Thread 0x7fff9d7fa700 (LWP 5481) exited]
[Thread 0x7fff9dffb700 (LWP 5480) exited]
[Thread 0x7fff9cff9700 (LWP 5482) exited]
[Thread 0x7fff9e7fc700 (LWP 5479) exited]
[Thread 0x7fffac959700 (LWP 5483) exited]Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fff9effd700 (LWP 5478)]
0x0000000000000000 in ?? ()
(gdb) bt
#0  0x0000000000000000 in ?? ()
#1  0x00007fffe3e69f92 in void apache::thrift::server::releaseOneDescriptor<boost::shared_ptr<apache::thrift::transport::TServerTransport> >(std::string const&, boost::shared_ptr<apache::thrift::transport::TServerTransport>&) ()
  from /usr/local/lib/libthrift-0.9.3.so
#2  0x00007fffe3e69495 in apache::thrift::server::TServerFramework::serve() ()
  from /usr/local/lib/libthrift-0.9.3.so
#3  0x00007fffe40afa4a in ?? ()
  from /usr/lib/x86_64-linux-gnu/libboost_thread.so.1.54.0
#4  0x00007ffff7bc4184 in start_thread (arg=0x7fff9effd700)
   at pthread_create.c:312
#5  0x00007ffff78f137d in clone ()
   at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111
```

It also dumps core with osmocom_fft -f 2.4e9. 

The issue apparently goes away after some iterations, but reappears if I unplug/plug the b200.

This seems to be a known issue, as I found this:
https://lists.gnu.org/archive/html/discuss-gnuradio/2015-08/msg00234.html
which quotes control port settings for Thrift (http://gnuradio.org/redmine/projects/gnuradio/wiki/ControlPort)

Apparently also thrift has to be set to be single threated (https://lists.gnu.org/archive/html/discuss-gnuradio/2016-08/msg00239.html) but I have to admit that I add this comment just as a reference and don't know for certain if the liveSDR is not setting this already.

**Comment by jmcorgan** [comment]
Indeed, this is a known issue related to Thrift shutdown.  Setting the thread count to 1 usually makes it go away.  I believe the issue has been fixed upstream at some point but we haven't seen a new release from them and it will need testing.  Fortunately, the issue doesn't effect normal operations, just the ugly message at shutdown of an application.

**Comment by jmcorgan** [comment]
As far as the shutdown patch referenced, it no long applies cleanly to their master, but again, I think they've addressed this already.  Might be worth experimenting with and getting back to us :+1:

**Comment by primercuervo** [comment]
If the issue is known, addressed, and confirmed that doesn't affect functionality, then I see no reason for now to keep this open. Thanks for the fast response!
